fix osc template

diff --git a/openstack/deploy/helm-charts/capi-cluster/charts/outscale/templates/Cluster.yaml b/openstack/deploy/helm-charts/capi-cluster/charts/outscale/templates/Cluster.yaml
--- a/openstack/deploy/helm-charts/capi-cluster/charts/outscale/templates/Cluster.yaml
+++ b/openstack/deploy/helm-charts/capi-cluster/charts/outscale/templates/Cluster.yaml
@@ -62,15 +62,16 @@ apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
 kind: OscCluster
 metadata:
   name: {{ .Values.global.clusterName }}
-  labels:
-    cluster.x-k8s.io/cluster-name: {{ .Values.global.clusterName }}
 spec:
   network:
+    clusterName: {{ .Values.global.clusterName }}
     bastion:
       enable: false
+      clusterName: {{ .Values.global.clusterName }}
     internetService:
-      name: {{ .Values.global.clusterName }}-internetservice
+      clusterName: {{ .Values.global.clusterName }}
     loadBalancer:
+      clusterName: {{ .Values.global.clusterName }}
       healthCheck:
         checkinterval: 5
         healthythreshold: 5
@@ -85,193 +86,159 @@ spec:
         loadbalancerprotocol: TCP
       loadbalancername: {{ .Values.global.clusterName }}-k8s
       loadbalancertype: internet-facing
-      securitygroupname: {{ .Values.global.clusterName }}-securitygroup-lb
-      subnetname: {{ .Values.global.clusterName }}-subnet-public
     natService:
-      name: {{ .Values.global.clusterName }}-natservice
-      publicipname: {{ .Values.global.clusterName }}-publicip-nat
-      subnetname: {{ .Values.global.clusterName }}-subnet-public
+      clusterName: {{ .Values.global.clusterName }}
     net:
-      ipRange: 10.0.0.0/16
-      name: {{ .Values.global.clusterName }}-net
-    publicIps:
-    - name: {{ .Values.global.clusterName }}-publicip-nat
-    routeTables:
-    - name: {{ .Values.global.clusterName }}-routetable-kw
-      routes:
-      - destination: 0.0.0.0/0
-        name: {{ .Values.global.clusterName }}-route-kw
-        targetName: {{ .Values.global.clusterName }}-natservice
-        targetType: nat
-      subnets:
-      - {{ .Values.global.clusterName }}-subnet-kw
-    - name: {{ .Values.global.clusterName }}-routetable-kcp
-      routes:
-      - destination: 0.0.0.0/0
-        name: {{ .Values.global.clusterName }}-route-kcp
-        targetName: {{ .Values.global.clusterName }}-natservice
-        targetType: nat
-      subnets:
-      - {{ .Values.global.clusterName }}-subnet-kcp
-    - name: {{ .Values.global.clusterName }}-routetable-public
-      routes:
-      - destination: 0.0.0.0/0
-        name: {{ .Values.global.clusterName }}-route-public
-        targetName: {{ .Values.global.clusterName }}-internetservice
-        targetType: gateway
-      subnets:
-      - {{ .Values.global.clusterName }}-subnet-public
-    securityGroups:
-    - description: Security Group Kw with {{ .Values.global.clusterName }}
-      name: {{ .Values.global.clusterName }}-securitygroup-kw
-      securityGroupRules:
-      - flow: Inbound
-        fromPortRange: 179
-        ipProtocol: tcp
-        ipRange: 10.0.0.0/16
-        name: {{ .Values.global.clusterName }}-securitygrouprule-kw-bgp
-        toPortRange: 179
-      - flow: Inbound
-        fromPortRange: 10250
-        ipProtocol: tcp
-        ipRange: 10.0.3.0/24
-        name: {{ .Values.global.clusterName }}-securitygrouprule-api-kubelet-kw
-        toPortRange: 10250
-      - flow: Inbound
-        fromPortRange: 30000
-        ipProtocol: tcp
-        ipRange: 10.0.4.0/24
-        name: {{ .Values.global.clusterName }}-securitygrouprule-kw-nodeip-kcp
-        toPortRange: 32767
-      - flow: Inbound
-        fromPortRange: 10250
-        ipProtocol: tcp
-        ipRange: 10.0.4.0/24
-        name: {{ .Values.global.clusterName }}-securitygrouprule-api-kubelet-kcp
-        toPortRange: 10250
-      - flow: Inbound
-        fromPortRange: 30000
-        ipProtocol: tcp
-        ipRange: 10.0.3.0/24
-        name: {{ .Values.global.clusterName }}-securitygrouprule-kw-nodeip-kw
-        toPortRange: 32767
-    - description: Security Group Kcp with {{ .Values.global.clusterName }}
-      name: {{ .Values.global.clusterName }}-securitygroup-kcp
-      securityGroupRules:
-      - flow: Inbound
-        fromPortRange: 179
-        ipProtocol: tcp
-        ipRange: 10.0.0.0/16
-        name: {{ .Values.global.clusterName }}-securitygrouprule-kcp-bgp
-        toPortRange: 179
-      - flow: Inbound
-        fromPortRange: 6443
-        ipProtocol: tcp
-        ipRange: 10.0.3.0/24
-        name: {{ .Values.global.clusterName }}-securitygrouprule-api-kw
-        toPortRange: 6443
-      - flow: Inbound
-        fromPortRange: 6443
-        ipProtocol: tcp
-        ipRange: 10.0.4.0/24
-        name: {{ .Values.global.clusterName }}-securitygrouprule-api-kcp
-        toPortRange: 6443
-      - flow: Inbound
-        fromPortRange: 30000
-        ipProtocol: tcp
-        ipRange: 10.0.3.0/24
-        name: {{ .Values.global.clusterName }}-securitygrouprule-kcp-nodeip-kw
-        toPortRange: 32767
-      - flow: Inbound
-        fromPortRange: 2378
-        ipProtocol: tcp
-        ipRange: 10.0.4.0/24
-        name: {{ .Values.global.clusterName }}-securitygrouprule-etcd
-        toPortRange: 2379
-      - flow: Inbound
-        fromPortRange: 10250
-        ipProtocol: tcp
-        ipRange: 10.0.4.0/24
-        name: {{ .Values.global.clusterName }}-securitygrouprule-kubelet-kcp
-        toPortRange: 10252
-      - flow: Inbound
-        fromPortRange: 30000
-        ipProtocol: tcp
-        ipRange: 10.0.4.0/24
-        name: {{ .Values.global.clusterName }}-securitugrouprule-kcp-nodeip-kcp
-        toPortRange: 32767
-    - description: Security Group Lb with {{ .Values.global.clusterName }}
-      name: {{ .Values.global.clusterName }}-securitygroup-lb
-      securityGroupRules:
-      - flow: Inbound
-        fromPortRange: 6443
-        ipProtocol: tcp
-        ipRange: 0.0.0.0/0
-        name: {{ .Values.global.clusterName }}-securitygrouprule-lb
-        toPortRange: 6443
-    - description: Security Group Node with {{ .Values.global.clusterName }}
-      name: {{ .Values.global.clusterName }}-securitygroup-node
-      securityGroupRules:
-      - flow: Inbound
-        fromPortRange: 4789
-        ipProtocol: udp
-        ipRange: 10.0.0.0/16
-        name: {{ .Values.global.clusterName }}-securitygroup-calico-vxlan
-        toPortRange: 4789
-      - flow: Inbound
-        fromPortRange: 5473
-        ipProtocol: udp
-        ipRange: 10.0.0.0/16
-        name: {{ .Values.global.clusterName }}-securitygroup-typha
-        toPortRange: 5473
-      - flow: Inbound
-        fromPortRange: 51820
-        ipProtocol: udp
-        ipRange: 10.0.0.0/16
-        name: {{ .Values.global.clusterName }}-securitygroup-wireguard
-        toPortRange: 51820
-      - flow: Inbound
-        fromPortRange: 51821
-        ipProtocol: udp
-        ipRange: 10.0.0.0/16
-        name: {{ .Values.global.clusterName }}-securitygroup-wireguard-ipv6
-        toPortRange: 51821
-      - flow: Inbound
-        fromPortRange: 4789
-        ipProtocol: udp
-        ipRange: 10.0.0.0/16
-        name: {{ .Values.global.clusterName }}-securitygroup-flannel
-        toPortRange: 4789
-      - flow: Inbound
-        fromPortRange: 8285
-        ipProtocol: udp
-        ipRange: 10.0.0.0/16
-        name: {{ .Values.global.clusterName }}-securitygroup-flannel-udp
-        toPortRange: 8285
-      - flow: Inbound
-        fromPortRange: 8472
-        ipProtocol: udp
-        ipRange: 10.0.0.0/16
-        name: {{ .Values.global.clusterName }}-securityrgroup-flannel-vxlan
-        toPortRange: 8472
-      tag: OscK8sMainSG
-    subnets:
-    - ipSubnetRange: 10.0.4.0/24
-      name: {{ .Values.global.clusterName }}-subnet-kcp
-      subregionName: {{ .Values.subregionName  }}
-    - ipSubnetRange: 10.0.3.0/24
-      name: {{ .Values.global.clusterName }}-subnet-kw
-      subregionName: {{ .Values.subregionName  }}
-    - ipSubnetRange: 10.0.2.0/24
-      name: {{ .Values.global.clusterName }}-subnet-public
-      subregionName: {{ .Values.subregionName  }}
+      clusterName: {{ .Values.global.clusterName }}
+#    securityGroups:
+#    - description: Security Group Kw with {{ .Values.global.clusterName }}
+#      name: {{ .Values.global.clusterName }}-securitygroup-kw
+#      securityGroupRules:
+#      - flow: Inbound
+#        fromPortRange: 179
+#        ipProtocol: tcp
+#        ipRange: 10.0.0.0/16
+#        name: {{ .Values.global.clusterName }}-securitygrouprule-kw-bgp
+#        toPortRange: 179
+#      - flow: Inbound
+#        fromPortRange: 10250
+#        ipProtocol: tcp
+#        ipRange: 10.0.3.0/24
+#        name: {{ .Values.global.clusterName }}-securitygrouprule-api-kubelet-kw
+#        toPortRange: 10250
+#      - flow: Inbound
+#        fromPortRange: 30000
+#        ipProtocol: tcp
+#        ipRange: 10.0.4.0/24
+#        name: {{ .Values.global.clusterName }}-securitygrouprule-kw-nodeip-kcp
+#        toPortRange: 32767
+#      - flow: Inbound
+#        fromPortRange: 10250
+#        ipProtocol: tcp
+#        ipRange: 10.0.4.0/24
+#        name: {{ .Values.global.clusterName }}-securitygrouprule-api-kubelet-kcp
+#        toPortRange: 10250
+#      - flow: Inbound
+#        fromPortRange: 30000
+#        ipProtocol: tcp
+#        ipRange: 10.0.3.0/24
+#        name: {{ .Values.global.clusterName }}-securitygrouprule-kw-nodeip-kw
+#        toPortRange: 32767
+#    - description: Security Group Kcp with {{ .Values.global.clusterName }}
+#      name: {{ .Values.global.clusterName }}-securitygroup-kcp
+#      securityGroupRules:
+#      - flow: Inbound
+#        fromPortRange: 179
+#        ipProtocol: tcp
+#        ipRange: 10.0.0.0/16
+#        name: {{ .Values.global.clusterName }}-securitygrouprule-kcp-bgp
+#        toPortRange: 179
+#      - flow: Inbound
+#        fromPortRange: 6443
+#        ipProtocol: tcp
+#        ipRange: 10.0.3.0/24
+#        name: {{ .Values.global.clusterName }}-securitygrouprule-api-kw
+#        toPortRange: 6443
+#      - flow: Inbound
+#        fromPortRange: 6443
+#        ipProtocol: tcp
+#        ipRange: 10.0.4.0/24
+#        name: {{ .Values.global.clusterName }}-securitygrouprule-api-kcp
+#        toPortRange: 6443
+#      - flow: Inbound
+#        fromPortRange: 30000
+#        ipProtocol: tcp
+#        ipRange: 10.0.3.0/24
+#        name: {{ .Values.global.clusterName }}-securitygrouprule-kcp-nodeip-kw
+#        toPortRange: 32767
+#      - flow: Inbound
+#        fromPortRange: 2378
+#        ipProtocol: tcp
+#        ipRange: 10.0.4.0/24
+#        name: {{ .Values.global.clusterName }}-securitygrouprule-etcd
+#        toPortRange: 2379
+#      - flow: Inbound
+#        fromPortRange: 10250
+#        ipProtocol: tcp
+#        ipRange: 10.0.4.0/24
+#        name: {{ .Values.global.clusterName }}-securitygrouprule-kubelet-kcp
+#        toPortRange: 10252
+#      - flow: Inbound
+#        fromPortRange: 30000
+#        ipProtocol: tcp
+#        ipRange: 10.0.4.0/24
+#        name: {{ .Values.global.clusterName }}-securitugrouprule-kcp-nodeip-kcp
+#        toPortRange: 32767
+#    - description: Security Group Lb with {{ .Values.global.clusterName }}
+#      name: {{ .Values.global.clusterName }}-securitygroup-lb
+#      securityGroupRules:
+#      - flow: Inbound
+#        fromPortRange: 6443
+#        ipProtocol: tcp
+#        ipRange: 0.0.0.0/0
+#        name: {{ .Values.global.clusterName }}-securitygrouprule-lb
+#        toPortRange: 6443
+#    - description: Security Group Node with {{ .Values.global.clusterName }}
+#      name: {{ .Values.global.clusterName }}-securitygroup-node
+#      securityGroupRules:
+#      - flow: Inbound
+#        fromPortRange: 4789
+#        ipProtocol: udp
+#        ipRange: 10.0.0.0/16
+#        name: {{ .Values.global.clusterName }}-securitygroup-calico-vxlan
+#        toPortRange: 4789
+#      - flow: Inbound
+#        fromPortRange: 5473
+#        ipProtocol: udp
+#        ipRange: 10.0.0.0/16
+#        name: {{ .Values.global.clusterName }}-securitygroup-typha
+#        toPortRange: 5473
+#      - flow: Inbound
+#        fromPortRange: 51820
+#        ipProtocol: udp
+#        ipRange: 10.0.0.0/16
+#        name: {{ .Values.global.clusterName }}-securitygroup-wireguard
+#        toPortRange: 51820
+#      - flow: Inbound
+#        fromPortRange: 51821
+#        ipProtocol: udp
+#        ipRange: 10.0.0.0/16
+#        name: {{ .Values.global.clusterName }}-securitygroup-wireguard-ipv6
+#        toPortRange: 51821
+#      - flow: Inbound
+#        fromPortRange: 4789
+#        ipProtocol: udp
+#        ipRange: 10.0.0.0/16
+#        name: {{ .Values.global.clusterName }}-securitygroup-flannel
+#        toPortRange: 4789
+#      - flow: Inbound
+#        fromPortRange: 8285
+#        ipProtocol: udp
+#        ipRange: 10.0.0.0/16
+#        name: {{ .Values.global.clusterName }}-securitygroup-flannel-udp
+#        toPortRange: 8285
+#      - flow: Inbound
+#        fromPortRange: 8472
+#        ipProtocol: udp
+#        ipRange: 10.0.0.0/16
+#        name: {{ .Values.global.clusterName }}-securityrgroup-flannel-vxlan
+#        toPortRange: 8472
+#      tag: OscK8sMainSG
+#    subnets:
+#    - ipSubnetRange: 10.0.4.0/24
+#      name: {{ .Values.global.clusterName }}-subnet-kcp
+#      subregionName: {{ .Values.subregionName  }}
+#    - ipSubnetRange: 10.0.3.0/24
+#      name: {{ .Values.global.clusterName }}-subnet-kw
+#      subregionName: {{ .Values.subregionName  }}
+#    - ipSubnetRange: 10.0.2.0/24
+#      name: {{ .Values.global.clusterName }}-subnet-public
+#      subregionName: {{ .Values.subregionName  }}
 ---
 apiVersion: cluster.x-k8s.io/v1beta1
 kind: MachineDeployment
 metadata:
   name: {{ .Values.global.clusterName }}
-  labels:
-    cluster.x-k8s.io/cluster-name: {{ .Values.global.clusterName }}
 spec:
   clusterName: {{ .Values.global.clusterName }}
   minReadySeconds: 0
@@ -279,19 +246,13 @@ spec:
   replicas: 1
   revisionHistoryLimit: 1
   selector:
-    matchLabels:
-      cluster.x-k8s.io/cluster-name: {{ .Values.global.clusterName }}
-      cluster.x-k8s.io/deployment-name: {{ .Values.global.clusterName }}
+    matchLabels: null
   strategy:
     rollingUpdate:
       maxSurge: 1
       maxUnavailable: 0
     type: RollingUpdate
   template:
-    metadata:
-      labels:
-        cluster.x-k8s.io/name: {{ .Values.global.clusterName }}
-        cluster.x-k8s.io/deployment-name: {{ .Values.global.clusterName }}
     spec:
       bootstrap:
         configRef:
@@ -303,7 +264,7 @@ spec:
         apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
         kind: OscMachineTemplate
         name: {{ .Values.global.clusterName }}-md-0
-      version: v1.29.1
+      version: v1.29.5
 ---
 apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
 kind: OscMachineTemplate
@@ -313,12 +274,14 @@ spec:
   template:
     spec:
       node:
+        clusterName: {{ .Values.global.clusterName }}
         image:
           name: {{ .Values.image }}
         keypair:
           name: {{ .Values.sshkeyname }}
           deleteKeypair: false
         vm:
+          clusterName: {{ .Values.global.clusterName }}
           keypairName: {{ .Values.sshkeyname }}
           rootDisk:
             rootDiskIops: 100
@@ -334,12 +297,14 @@ spec:
   template:
     spec:
       node:
+        clusterName: {{ .Values.global.clusterName }}
         image:
           name: {{ .Values.image }}
         keypair:
           name: {{ .Values.sshkeyname }}
           deleteKeypair: false
         vm:
+          clusterName: {{ .Values.global.clusterName }}
           keypairName: {{ .Values.sshkeyname }}
           loadBalancerName: {{ .Values.global.clusterName }}-k8s
           role: controlplane
@@ -365,7 +330,6 @@ spec:
         owner: root:root
         path: /tmp/set_runc.sh
         permissions: "0744"
-      format: cloud-config
       joinConfiguration:
         nodeRegistration:
           imagePullPolicy: IfNotPresent
@@ -380,20 +344,73 @@ apiVersion: controlplane.cluster.x-k8s.io/v1beta1
 kind: KubeadmControlPlane
 metadata:
   name: {{ .Values.global.clusterName }}-control-plane
-  labels:
-    cluster.x-k8s.io/cluster-name: {{ .Values.global.clusterName }}
 spec:
   kubeadmConfigSpec:
+    preKubeadmCommands:
+      - echo debug-pre > /tmp/out
+      - mkdir -p /etc/pre-kubeadm-commands
+      - for script in $(find /etc/pre-kubeadm-commands/ -name '*.sh' -type f | sort);
+        do echo "Running script $script"; "$script"; done
+    postKubeadmCommands:
+      - echo debug-post >> /tmp/out
+      - mkdir -p /etc/post-kubeadm-commands
+      - for script in $(find /etc/post-kubeadm-commands/ -name '*.sh' -type f | sort);
+        do echo "Running script $script"; "$script"; done
     files:
+    - content: |
+        #!/bin/bash
+        grep '^      limits:' /etc/kubernetes/manifests/kube-apiserver.yaml >/dev/null 2>&1 && exit 0
+        MEM=$(free -m | grep '^Mem:' | awk '{print $2;}')
+        CPU=$(grep '^processor' /proc/cpuinfo | wc -l)
+        sed -i "/^ *requests:/i\      limits:\n        memory: $((10+3*$MEM/4))M\n        cpu: $((750*$CPU))m" /etc/kubernetes/manifests/kube-apiserver.yaml
+        sed -i "/^ *requests:/a\        memory: 512M" /etc/kubernetes/manifests/kube-apiserver.yaml
+        sync
+        systemctl restart kubelet
+      owner: root:root
+      path: /etc/post-kubeadm-commands/10-tweak-kubeapi-memlimit.sh
+      permissions: "0700"
     - content: |
         #!/bin/sh
         curl https://github.com/opencontainers/runc/releases/download/v1.1.1/runc.amd64 -Lo /tmp/runc.amd64
         chmod +x /tmp/runc.amd64
         cp -f /tmp/runc.amd64 /usr/local/sbin/runc
       owner: root:root
-      path: /tmp/set_runc.sh
+      path: /etc/pre-kubeadm-commands/10-set_runc.sh
       permissions: "0744"
-    format: cloud-config
+    - content: |
+        #!/bin/bash
+        set +e
+        # Define the retry function
+        wait_and_retry() {
+          local retries="$1"
+          local wait="$2"
+          local command="$3"
+
+          $command
+          local exit_code=$?
+
+          if [[ $exit_code -ne 0 && $retries -gt 0 ]]; then
+            echo "# Wait $wait before retrying $retries"
+            sleep $wait
+            wait_and_retry $(($retries - 1)) $wait "$command"
+          else
+            return $exit_code
+          fi
+        }
+        echo "ds.meta_data.hostname {{ ds.meta_data.hostname }}"
+        endpoint=$(grep "controlPlaneEndpoint" /run/kubeadm/kubeadm.yaml|awk ' {print $2 }' |sed -e 's/ //g;s/:.*//g')
+
+        wait_and_retry 360 10 "host $endpoint"
+      owner: root:root
+      path: /etc/pre-kubeadm-commands/00-wait_endpoint.sh
+      permissions: "0755"
+#    clusterConfiguration:
+#      apiServer:
+#        extraArgs:
+#          cloud-provider: external
+#      controllerManager:
+#        extraArgs:
+#          cloud-provider: external
     initConfiguration:
       nodeRegistration:
         imagePullPolicy: IfNotPresent
@@ -407,8 +424,7 @@ spec:
         kubeletExtraArgs:
           cloud-provider: external
           provider-id: {{`'aws:///{{ ds.meta_data.placement.availability_zone }}/{{ ds.meta_data.instance_id }}'`}}
-    preKubeadmCommands:
-    - sh /tmp/set_runc.sh
+    verbosity: 10
   machineTemplate:
     infrastructureRef:
       apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
@@ -419,4 +435,4 @@ spec:
     rollingUpdate:
       maxSurge: 1
     type: RollingUpdate
-  version: v1.29.1
+  version: v1.29.5
